# Generated by Django 3.2.6 on 2021-08-14 08:25

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramBot', '0003_remove_cliente_primo_acquisto'),
    ]

    operations = [
        migrations.CreateModel(
            name='OneTimePassword',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codice', models.CharField(default='Mp10ibWhkwnj2JTRnYjo98g5my22HEgYLgy0epv181FunKspQj', max_length=50)),
                ('valido_fino', models.DateField(blank=True)),
                ('generato', models.DateTimeField(default=datetime.datetime(2021, 8, 14, 10, 25, 22, 355959))),
                ('usato', models.DateTimeField(blank=True)),
                ('utilizzato', models.BooleanField(default=False)),
                ('cliente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='TelegramBot.cliente')),
            ],
        ),
    ]
