# Generated by Django 3.2.6 on 2021-08-14 08:29

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramBot', '0004_onetimepassword'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='cliente',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='TelegramBot.cliente'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='codice',
            field=models.CharField(default='hjzM5EsBwQMQvH1UpyBXk0P6Kb0LWiCLPJDHsQjuyaE7o4BCdD', max_length=50),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='generato',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 10, 29, 8, 56167)),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='utilizzato',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
