# Generated by Django 3.2.6 on 2021-08-14 08:35

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramBot', '0005_auto_20210814_1029'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='codice',
            field=models.CharField(default='n9ntBTgpD0rI0ztV0HY9lnhARKSzhhylQEoFHYKlK7wdvwFiDH', max_length=50),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='generato',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 10, 35, 6, 834293)),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='usato',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
