# Generated by Django 3.2.6 on 2021-08-14 08:38

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramBot', '0006_auto_20210814_1035'),
    ]

    operations = [
        migrations.AlterField(
            model_name='onetimepassword',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='TelegramBot.cliente'),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='codice',
            field=models.CharField(default='eh6G4uuFFKNUSahK1XoHtmkfJSLZYuku57mUnLNYdgbiij7RYn', max_length=50),
        ),
        migrations.AlterField(
            model_name='onetimepassword',
            name='generato',
            field=models.DateTimeField(default=datetime.datetime(2021, 8, 14, 10, 38, 1, 554315)),
        ),
    ]
