# Generated by Django 3.2.6 on 2021-08-14 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('TelegramBot', '0007_auto_20210814_1038'),
    ]

    operations = [
        migrations.AddField(
            model_name='cliente',
            name='verificato',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.DeleteModel(
            name='OneTimePassword',
        ),
    ]
